
services:
  radioamatori_lezioni_web:
    container_name: radioamatori_lezioni_web
    image: manzolo/radioamatori_lezioni
    volumes:
      - ./media:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    #depends_on:
    #  - radioamatori_lezioni_db
    networks:
      - radioamatori_lezioni_net

  radioamatori_lezioni_nginx:
    image: nginx:latest
    container_name: radioamatori_lezioni_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/static
    depends_on:
      - radioamatori_lezioni_web
    networks:
      - radioamatori_lezioni_net

volumes:
  static_volume: {}

networks:
  radioamatori_lezioni_net:
    driver: bridge