services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: radioamatori_lezioni_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}  # Modifica nel .env
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}        # Modifica nel .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - radioamatori_lezioni_db
    networks:
      - radioamatori_lezioni_net


  radioamatori_lezioni_db:
    image: postgres:17  # o postgres:13 se preferisci
    container_name: radioamatori_lezioni_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - radioamatori_lezioni_net

volumes:
  pgadmin_data: {}
  postgres_data: {}

networks:
  radioamatori_lezioni_net:
    driver: bridge
    external: true