services:
  radioamatori_lezioni_web:
    container_name: radioamatori_lezioni_web
    image: manzolo/radioamatori_lezioni
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./db:/app/db
      - ./media:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    #environment:
    #  DJANGO_SETTINGS_MODULE: lezioni_progetto.settings
    #  ALLOWED_HOSTS: "localhost,127.0.0.1,127.0.0.1:8000,localhost:8000,[::1]"
    #  SECRET_KEY: "changeme"
    #  DEBUG: 1
    env_file:
      - .env

  radioamatori_lezioni_nginx:
    image: nginx:latest
    container_name: radioamatori_lezioni_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/static
    depends_on:
      - radioamatori_lezioni_web

volumes:
  static_volume: {}