# Generated by Django 5.2 on 2025-04-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('titolo', models.CharField(max_length=200)),
                ('url_video', models.URLField()),
                ('file_slide', models.FileField(upload_to='documenti/slide/')),
                ('file_domande', models.FileField(upload_to='documenti/domande/')),
                ('file_risposte', models.FileField(upload_to='documenti/risposte/')),
            ],
        ),
    ]
