# Generated by Django 5.2 on 2025-04-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezione',
            name='data_lezione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='file_domande',
            field=models.FileField(blank=True, null=True, upload_to='documenti/domande/'),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='file_risposte',
            field=models.FileField(blank=True, null=True, upload_to='documenti/risposte/'),
        ),
        migrations.AlterField(
            model_name='lezione',
            name='file_slide',
            field=models.FileField(blank=True, null=True, upload_to='documenti/slide/'),
        ),
    ]
