# Generated by Django 5.2 on 2025-05-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lezioni', '0003_docente_lezione_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezione',
            name='file_allegati',
            field=models.FileField(blank=True, null=True, upload_to='documenti/allegati/'),
        ),
    ]
